# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-image .

      - name: List Docker Image
        run: |
          docker image ls

      # Start Docker container
      - name: Start Docker container
        run: |
          docker run -d -p 8080:8080 --name my-container my-image

      # Wait for a few seconds to ensure the container is up
      - name: Wait for container to be ready
        run: |
          Start-Sleep -Seconds 8

      - name: List Docker Container
        run: |
          docker ps -a

      # Print content from the application using curl
      - name: Curl application content
        run: |
          curl http://localhost:8080

      # Wait for a few seconds to ensure the container is up
      - name: Wait for container to be ready
        run: |
          Start-Sleep -Seconds 5

      # Print content from the application using curl
      - name: Curl application content
        run: |
          curl http://localhost:8080/java-hello-world

      # Optionally, stop and remove the container after testing
      - name: Cleanup Docker container
        run: |
          docker stop my-container
          docker rm my-container